inserir_dados_cidades_RO = {
	'1':'Alta Floresta d´Oeste',
	'2':'Ariquemes',
	'3':'Cabixi',
	'4':'Cacoal',
	'5':'Cerejeiras',
	'6':'Colorado do Oeste',
	'7':'Corumbiara',
	'8':'Costa Marques',
	'9':'Espigão d´Oeste',
	'10':'Guajará-Mirim',
	'11':'Jaru',
	'12':'Ji-Paraná',
	'13':'Machadinho d´Oeste',
	'14':'Nova Brasilândia d´Oeste',
	'15':'Ouro Preto do Oeste',
	'16':'Pimenta Bueno',
	'17':'Porto Velho',
	'18':'Presidente Médici',
	'19':'Rio Crespo',
	'20':'Rolim de Moura',
	'21':'Santa Luzia d´Oeste',
	'22':'Vilhena',
	'23':'São Miguel do Guaporé',
	'24':'Nova Mamoré',
	'25':'Alvorada d´Oeste',
	'26':'Alto Alegre dos Parecis',
	'27':'Alto Paraíso',
	'28':'Buritis',
	'29':'Novo Horizonte do Oeste',
	'30':'Cacaulândia',
	'31':'Campo Novo de Rondônia',
	'32':'Candeias do Jamari',
	'33':'Castanheiras',
	'34':'Chupinguaia',
	'35':'Cujubim',
	'36':'Governador Jorge Teixeira',
	'37':'Itapuã do Oeste',
	'38':'Ministro Andreazza',
	'39':'Mirante da Serra',
	'40':'Monte Negro',
	'41':'Nova União',
	'42':'Parecis',
	'43':'Pimenteiras do Oeste',
	'44':'Primavera de Rondônia',
	'45':'São Felipe d´Oeste',
	'46':'São Francisco do Guaporé',
	'47':'Seringueiras',
	'48':'Teixeirópolis',
	'49':'Theobroma',
	'50':'Urupá',
	'51':'Vale do Anari',
	'52':'Vale do Paraíso'
}

inserir_dados_cidades_AC = {
	'1':'Acrelândia',
	'2':'Assis Brasil',
	'3':'Brasiléia',
	'4':'Bujari',
	'5':'Capixaba',
	'6':'Cruzeiro do Sul',
	'7':'Epitaciolândia',
	'8':'Feijó',
	'9':'Jordão',
	'10':'Mâncio Lima',
	'11':'Manoel Urbano',
	'12':'Marechal Thaumaturgo',
	'13':'Plácido de Castro',
	'14':'Porto Walter',
	'15':'Rio Branco',
	'16':'Rodrigues Alves',
	'17':'Santa Rosa do Purus',
	'18':'Senador Guiomard',
	'19':'Sena Madureira',
	'20':'Tarauacá',
	'21':'Xapuri',
	'22':'Porto Acre'
}